# Generated by Django 4.2.4 on 2023-12-03 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='vessel_load_calculation',
        ),
    ]
