# Generated by Django 4.2.4 on 2023-12-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_assignment_vessel_load_calculation'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='vessel_load_calculation',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
