# Generated by Django 4.2.4 on 2023-12-09 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_assignment_vessel_load_calculation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routeship',
            name='route_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
