# Generated by Django 5.0 on 2024-01-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_routeship_route_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='ship',
            name='crew',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
